Repository wanted-quantum-jump/FoodieFinder, pull requests merged in 2023-11, with the labels that each got.

#12 feat : Restaurant 엔티티 구현
  src/main/java/com/foodiefinder/common/config/JpaConfig.java
  src/main/java/com/foodiefinder/common/entity/BaseTimeEntity.java
  src/main/java/com/foodiefinder/datapipeline/writer/entity/RawRestaurant.java
  src/main/java/com/foodiefinder/datapipeline/writer/entity/Restaurant.java
  src/main/java/com/foodiefinder/datapipeline/writer/repository/RawRestaurantRepository.java
  src/main/java/com/foodiefinder/datapipeline/writer/repository/RestaurantRepository.java
  src/test/java/com/foodiefinder/config/RepositoryUnitTest.java
  src/test/java/com/foodiefinder/datapipeline/writer/repository/RawRestaurantRepositoryTest.java
  src/test/java/com/foodiefinder/datapipeline/writer/repository/RestaurantRepositoryTest.java
Labels: enhancement

#23 feat : 시군구 CSV 데이터를 DB에 저장
  build.gradle
  src/main/java/com/foodiefinder/common/exception/ErrorCode.java
  src/main/java/com/foodiefinder/datapipeline/processor/SggProcessor.java
  src/main/java/com/foodiefinder/datapipeline/writer/SggWriter.java
  src/main/java/com/foodiefinder/datapipeline/writer/entity/Sgg.java
  src/main/java/com/foodiefinder/datapipeline/writer/repository/SggRepository.java
  src/main/resources/sgg_lat_lon.csv
Labels: enhancement

#24 feat: Spring Quartz 설정, reader, 재시도 기능 구현
  src/main/java/com/foodiefinder/datapipeline/config/BatchConfig.java
  src/main/java/com/foodiefinder/datapipeline/config/QuartzConfig.java
  src/main/java/com/foodiefinder/datapipeline/enums/JobState.java
  src/main/java/com/foodiefinder/datapipeline/enums/OpenApiUrl.java
  src/main/java/com/foodiefinder/datapipeline/job/JobStateHandler.java
  src/main/java/com/foodiefinder/datapipeline/job/OpenApiJob.java
  src/main/java/com/foodiefinder/datapipeline/job/StateHandler.java
  src/main/java/com/foodiefinder/datapipeline/processor/ItemProcessor.java
  src/main/java/com/foodiefinder/datapipeline/provider/UrlProvider.java
  src/main/java/com/foodiefinder/datapipeline/provider/UrlWithParamsProvider.java
  src/main/java/com/foodiefinder/datapipeline/reader/AbstractPagingItemReader.java
  src/main/java/com/foodiefinder/datapipeline/reader/ItemReader.java
  src/main/java/com/foodiefinder/datapipeline/reader/OpenApiPagingItemReader.java
  src/main/java/com/foodiefinder/datapipeline/step/ChunkOrientedStep.java
  src/main/java/com/foodiefinder/datapipeline/step/OpenApiItemStep.java
  src/main/java/com/foodiefinder/datapipeline/step/Step.java
  src/main/java/com/foodiefinder/datapipeline/util/HttpRequest.java
  src/main/java/com/foodiefinder/datapipeline/writer/ItemWriter.java
  src/main/resources/application.properties
Labels: enhancement

#26 feat : raw data 전처리
  build.gradle
  src/main/java/com/foodiefinder/common/exception/ErrorCode.java
  src/main/java/com/foodiefinder/datapipeline/processor/RawRestaurantProcessor.java
  src/main/java/com/foodiefinder/datapipeline/processor/dto/RootData.java
  src/main/java/com/foodiefinder/datapipeline/writer/entity/RawRestaurant.java
  src/test/java/com/foodiefinder/datapipeline/processor/RawRestaurantProcessorTest.java
  src/test/java/com/foodiefinder/datapipeline/writer/repository/RawRestaurantRepositoryTest.java
Labels: enhancement

#32 fix : 경기도 일반 음식점 업종 반영하지 못하는 오류 수정
  src/main/java/com/foodiefinder/datapipeline/processor/dto/RootData.java
Labels: bug, enhancement

#29 feat: 회원가입 API 구현
  build.gradle
  src/main/java/com/foodiefinder/user/controller/UserController.java
  src/main/java/com/foodiefinder/user/crypto/PasswordEncoder.java
  src/main/java/com/foodiefinder/user/dto/UserSignupRequest.java
  src/main/java/com/foodiefinder/user/entity/User.java
  src/main/java/com/foodiefinder/user/repository/UserRepository.java
  src/main/java/com/foodiefinder/user/service/UserService.java
  src/test/java/com/foodiefinder/user/controller/UserControllerTest.java
  src/test/java/com/foodiefinder/user/service/UserServiceTest.java
Labels: enhancement

#31 feat : Raw 데이터 저장 기능 구현
  build.gradle
  src/main/java/com/foodiefinder/datapipeline/writer/RawRestaurantWriter.java
  src/test/java/com/foodiefinder/datapipeline/processor/RawRestaurantProcessorTest.java
  src/test/java/com/foodiefinder/datapipeline/writer/RawRestaurantWriterIntegretionTest.java
  src/test/java/com/foodiefinder/datapipeline/writer/RawRestaurantWriterTest.java
Labels: enhancement

#34 feat: 시군구 목록 API
  src/main/java/com/foodiefinder/cities/controller/CityController.java
  src/main/java/com/foodiefinder/cities/controller/response/CitesResponse.java
  src/main/java/com/foodiefinder/cities/controller/response/CitesResponses.java
  src/main/java/com/foodiefinder/cities/domain/SggList.java
  src/main/java/com/foodiefinder/cities/factory/SggListFactory.java
  src/main/java/com/foodiefinder/cities/service/CityService.java
  src/main/java/com/foodiefinder/common/dto/Response.java
  src/main/java/com/foodiefinder/common/exception/ErrorCode.java
  src/test/java/com/foodiefinder/cities/CityControllerTest.java
  src/test/java/com/foodiefinder/cities/CityServiceTest.java
Labels: enhancement

#41 refactor: Quartz 데이터 파이프라인, reader 테스트, 로깅 추가 및 리팩토링
  src/main/java/com/foodiefinder/datapipeline/config/BatchConfig.java
  src/main/java/com/foodiefinder/datapipeline/config/QuartzConfig.java
  src/main/java/com/foodiefinder/datapipeline/job/JobStateHandler.java
  src/main/java/com/foodiefinder/datapipeline/job/OpenApiJob.java
  src/main/java/com/foodiefinder/datapipeline/job/OpenApiJobFailedListener.java
  src/main/java/com/foodiefinder/datapipeline/reader/AbstractPagingItemReader.java
  src/main/java/com/foodiefinder/datapipeline/reader/OpenApiPagingItemReader.java
  src/main/java/com/foodiefinder/datapipeline/step/ChunkOrientedStep.java
  src/main/java/com/foodiefinder/datapipeline/util/HttpRequest.java
  src/main/java/com/foodiefinder/datapipeline/util/RequestStrategy.java
  src/main/java/com/foodiefinder/datapipeline/util/UrlParamsRequestStrategy.java
  src/main/java/com/foodiefinder/datapipeline/util/UrlProvider.java
  src/main/java/com/foodiefinder/datapipeline/util/UrlWithParamsProvider.java
  src/test/java/com/foodiefinder/datapipeline/reader/OpenApiPagingItemReaderTest.java
  src/test/java/com/foodiefinder/datapipeline/step/ChunkOrientedStepTest.java
Labels: bug

#46 feat: reader, processor, writer 기능 배치에 등록
  src/main/java/com/foodiefinder/datapipeline/config/BatchConfig.java
  src/main/java/com/foodiefinder/datapipeline/enums/OpenApiUrl.java
  src/main/java/com/foodiefinder/datapipeline/job/OpenApiJob.java
  src/main/java/com/foodiefinder/datapipeline/processor/CombineRestaurantProcessor.java
  src/main/java/com/foodiefinder/datapipeline/processor/dto/CombineRestaurantProcessorResultData.java
  src/main/java/com/foodiefinder/datapipeline/processor/dto/RootData.java
  src/main/java/com/foodiefinder/datapipeline/writer/CombineRestaurantWriter.java
  src/main/java/com/foodiefinder/datapipeline/writer/RawRestaurantWriter.java
  src/main/java/com/foodiefinder/datapipeline/writer/RestaurantWriter.java
  src/main/java/com/foodiefinder/datapipeline/writer/repository/RawRestaurantRepository.java
  src/main/java/com/foodiefinder/datapipeline/writer/repository/RestaurantRepository.java
  src/main/resources/application.properties
Labels: enhancement

#51 feature: 유저 상세, 유저 정보 변경 API 구현 및 점심추천기능 테이블 분리
  src/main/java/com/foodiefinder/user/controller/UserController.java
  src/main/java/com/foodiefinder/user/dto/UserDetailResponse.java
  src/main/java/com/foodiefinder/user/dto/UserInfoUpdateRequest.java
  src/main/java/com/foodiefinder/user/entity/LunchRecommendationSettings.java
  src/main/java/com/foodiefinder/user/entity/User.java
  src/main/java/com/foodiefinder/user/repository/LunchRecommendationSettingsRepository.java
  src/main/java/com/foodiefinder/user/service/UserService.java
  src/test/java/com/foodiefinder/user/controller/UserControllerTest.java
  src/test/java/com/foodiefinder/user/service/UserServiceTest.java
Labels: enhancement

#48 fix: 로그인 시 응답 토큰 형식 추가
  src/main/java/com/foodiefinder/auth/controller/AuthController.java
Labels: bug

#57 feat: 맛집 상세 API
  src/main/java/com/foodiefinder/common/dto/Response.java
  src/main/java/com/foodiefinder/common/exception/ErrorCode.java
  src/main/java/com/foodiefinder/datapipeline/writer/entity/Restaurant.java
  src/main/java/com/foodiefinder/restaurants/controller/RestaurantsController.java
  src/main/java/com/foodiefinder/restaurants/dto/RatingDto.java
  src/main/java/com/foodiefinder/restaurants/dto/RatingRequest.java
  src/main/java/com/foodiefinder/restaurants/dto/RestaurantDetailResponse.java
  src/main/java/com/foodiefinder/restaurants/dto/RestaurantsResponse.java
  src/main/java/com/foodiefinder/restaurants/entity/Rating.java
  src/main/java/com/foodiefinder/restaurants/entity/RatingRepository.java
  src/main/java/com/foodiefinder/restaurants/service/RatingService.java
  src/main/java/com/foodiefinder/restaurants/service/RestaurantsService.java
  src/test/java/com/foodiefinder/restaurants/controller/RestaurantsControllerTest.java
  src/test/java/com/foodiefinder/restaurants/service/RestaurantsServiceTest.java
Labels: enhancement

#56 feat: 맛집 평가 API
  src/test/java/com/foodiefinder/restaurants/controller/RestaurantsControllerTest.java
  src/test/java/com/foodiefinder/restaurants/service/RatingServiceTest.java
Labels: enhancement

#60 fix : 목록 조회 관련 오류 수정
  src/main/java/com/foodiefinder/common/exception/ErrorCode.java
  src/main/java/com/foodiefinder/restaurants/controller/RestaurantsController.java
  src/main/java/com/foodiefinder/restaurants/dto/RestaurantDetailResponse.java
  src/main/java/com/foodiefinder/restaurants/service/RestaurantsService.java
  src/test/java/com/foodiefinder/restaurants/controller/RestaurantsControllerTest.java
  src/test/java/com/foodiefinder/restaurants/service/RestaurantsServiceTest.java
Labels: bug

#63 feat: refresh토큰 발급 추가 및 액세스토큰 재발급 api 구현
  src/main/java/com/foodiefinder/auth/config/SecurityConfig.java
  src/main/java/com/foodiefinder/auth/controller/AuthController.java
  src/main/java/com/foodiefinder/auth/jwt/JwtUtils.java
  src/main/java/com/foodiefinder/auth/service/AuthService.java
  src/test/java/com/foodiefinder/auth/controller/AuthControllerTest.java
  src/test/java/com/foodiefinder/auth/service/AuthServiceTest.java
Labels: enhancement

#62 refactor : 데이터 전처리, 저장 리펙토링
  src/main/java/com/foodiefinder/datapipeline/processor/dto/RootData.java
  src/test/java/com/foodiefinder/datapipeline/processor/RawRestaurantProcessorTest.java
  src/test/java/com/foodiefinder/datapipeline/writer/RawRestaurantWriterIntegretionTest.java
  src/test/java/com/foodiefinder/datapipeline/writer/RawRestaurantWriterTest.java
  src/test/java/com/foodiefinder/datapipeline/writer/RestaurantWriterIntegretionTest.java
  src/test/java/com/foodiefinder/datapipeline/writer/RestaurantWriterTest.java
  src/test/java/com/foodiefinder/datapipeline/writer/repository/RawRestaurantRepositoryTest.java
  src/test/java/com/foodiefinder/datapipeline/writer/repository/RestaurantRepositoryTest.java
Labels: enhancement

#52 feat : 디스코드 웹 훅을 활용한 점심 추천 서비스 구현
  build.gradle
  src/main/java/com/foodiefinder/datapipeline/writer/repository/RestaurantRepository.java
  src/main/java/com/foodiefinder/notification/dto/DiscordMessageDto.java
  src/main/java/com/foodiefinder/notification/dto/Message.java
  src/main/java/com/foodiefinder/notification/repository/NotificationSettingRepository.java
  src/main/java/com/foodiefinder/notification/scheduler/DiscordNotificationJob.java
  src/main/java/com/foodiefinder/notification/scheduler/DiscordNotificationQuartzConfig.java
  src/main/java/com/foodiefinder/notification/service/DiscordLunchNotificationService.java
  src/main/java/com/foodiefinder/notification/service/GeoUtils.java
  src/main/java/com/foodiefinder/settings/controller/NotificationSettingController.java
  src/main/java/com/foodiefinder/settings/dto/ChangeNotificationSettingRequest.java
  src/main/java/com/foodiefinder/settings/entity/NotificationSetting.java
  src/main/java/com/foodiefinder/settings/service/NotificationSettingService.java
  src/main/java/com/foodiefinder/settings/valid/RecommendationCategoriesValidator.java
  src/main/java/com/foodiefinder/settings/valid/ValidRecommendationCategories.java
  src/main/java/com/foodiefinder/user/dto/UserDetailResponse.java
  src/main/java/com/foodiefinder/user/dto/UserInfoUpdateRequest.java
  src/main/java/com/foodiefinder/user/entity/LunchRecommendationSettings.java
  src/main/java/com/foodiefinder/user/repository/LunchRecommendationSettingsRepository.java
  src/main/java/com/foodiefinder/user/service/UserService.java
  src/test/java/com/foodiefinder/notification/service/DiscordLunchNotificationServiceTest.java
  src/test/java/com/foodiefinder/settings/controller/NotificationSettingControllerTest.java
  src/test/java/com/foodiefinder/settings/service/NotificationSettingServiceTest.java
  src/test/java/com/foodiefinder/settings/valid/RecommendationCategoriesValidatorTest.java
  src/test/java/com/foodiefinder/user/controller/UserControllerTest.java
  src/test/java/com/foodiefinder/user/service/UserServiceTest.java
Labels: enhancement

#65 feat: 레디스를 활용한 캐싱 기능 추가
  build.gradle
  src/main/java/com/foodiefinder/common/cache/CacheUtils.java
  src/main/java/com/foodiefinder/common/enums/CacheKeyPrefix.java
  src/main/java/com/foodiefinder/datapipeline/cache/DataPipelineApiResponseCacheRepository.java
  src/main/java/com/foodiefinder/datapipeline/cache/DataPipelineRestaurantCacheRepository.java
  src/main/java/com/foodiefinder/datapipeline/cache/DataPipelineSggCacheRepository.java
  src/main/java/com/foodiefinder/datapipeline/config/BatchConfig.java
  src/main/java/com/foodiefinder/datapipeline/enums/OpenApiUrl.java
  src/main/java/com/foodiefinder/datapipeline/processor/CombineRestaurantProcessor.java
  src/main/java/com/foodiefinder/datapipeline/processor/dto/CombineRestaurantProcessorResultData.java
  src/main/java/com/foodiefinder/datapipeline/processor/dto/RootData.java
  src/main/java/com/foodiefinder/datapipeline/reader/OpenApiPagingItemReader.java
  src/main/java/com/foodiefinder/datapipeline/step/ChunkOrientedStep.java
  src/main/java/com/foodiefinder/datapipeline/util/hash/HashGenerator.java
  src/main/java/com/foodiefinder/datapipeline/util/request/RequestStrategy.java
  src/main/java/com/foodiefinder/datapipeline/util/request/UrlParamsRequestStrategy.java
  src/main/java/com/foodiefinder/datapipeline/util/request/UrlProvider.java
  src/main/java/com/foodiefinder/datapipeline/util/request/UrlWithParamsProvider.java
  src/main/java/com/foodiefinder/datapipeline/writer/ApiResponseCacheWriter.java
  src/main/java/com/foodiefinder/datapipeline/writer/CombineRestaurantWriter.java
  src/main/java/com/foodiefinder/datapipeline/writer/RestaurantCacheWriter.java
  src/main/java/com/foodiefinder/datapipeline/writer/SggCacheWriter.java
  src/main/java/com/foodiefinder/datapipeline/writer/dto/RestaurantCacheDto.java
  src/main/java/com/foodiefinder/datapipeline/writer/repository/ForCacheRestaurantRepository.java
  src/main/java/com/foodiefinder/restaurants/cache/RatingCacheRepository.java
  src/main/java/com/foodiefinder/restaurants/cache/RestaurantCacheRepository.java
  src/main/java/com/foodiefinder/restaurants/cache/RestaurantDetailCacheRepository.java
  src/main/java/com/foodiefinder/restaurants/controller/RestaurantsController.java
  src/main/java/com/foodiefinder/restaurants/dto/RestaurantCacheResponse.java
  src/main/java/com/foodiefinder/restaurants/dto/RestaurantDetailResponse.java
  src/main/java/com/foodiefinder/restaurants/enums/RestaurantSortOption.java
  src/main/java/com/foodiefinder/restaurants/service/RatingService.java
  src/main/java/com/foodiefinder/restaurants/service/RestaurantsService.java
  src/main/resources/application.properties
  src/main/resources/sgg_lat_lon.csv
  src/test/java/com/foodiefinder/datapipeline/reader/OpenApiPagingItemReaderTest.java
Labels: enhancement

#69 fix: 캐싱 open, close pipeline 개선과 jwt 에러 수정
  src/main/java/com/foodiefinder/auth/jwt/JwtUtils.java
  src/main/java/com/foodiefinder/datapipeline/cache/DataPipelineRestaurantCacheRepository.java
Labels: bug

#70 refactor: 캐싱 기능 리팩토링
  src/main/java/com/foodiefinder/common/cache/CacheUtils.java
  src/main/java/com/foodiefinder/datapipeline/cache/DataPipelineApiResponseCacheRepository.java
  src/main/java/com/foodiefinder/datapipeline/cache/DataPipelineRestaurantCacheRepository.java
  src/main/java/com/foodiefinder/datapipeline/cache/SggCacheRepository.java
  src/main/java/com/foodiefinder/datapipeline/processor/CombineRestaurantProcessor.java
  src/main/java/com/foodiefinder/datapipeline/writer/RestaurantCacheWriter.java
  src/main/java/com/foodiefinder/datapipeline/writer/SggCacheWriter.java
  src/main/java/com/foodiefinder/restaurants/cache/RatingCacheRepository.java
  src/main/java/com/foodiefinder/restaurants/cache/RestaurantCacheForModifyRatingRepository.java
  src/main/java/com/foodiefinder/restaurants/cache/RestaurantCacheRepository.java
  src/main/java/com/foodiefinder/restaurants/cache/RestaurantCacheSearchRepository.java
  src/main/java/com/foodiefinder/restaurants/cache/RestaurantDetailCacheRepository.java
  src/main/java/com/foodiefinder/restaurants/service/RatingService.java
  src/main/java/com/foodiefinder/restaurants/service/RestaurantsService.java
Labels: enhancement
